[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.5", features = ["full"] }
alloy-consensus = "0.3.6"
alloy-rlp = "0.3.8"
tokio = { version = "1", features = ["full"] }
