[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "Cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "forge-std/=lib/forge-std/src/",
    "Solidity-RLP/=lib/Solidity-RLP/contracts/",
    "optimism/=lib/optimism/packages/contracts-bedrock/src/",
]

fs_permissions = [{ access = 'read', path = './test/res/' }]


[fmt]
sort_imports = true
wrap_comments = true
